apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: feedbacks-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: feedbacks
    spec:
      containers:
      - image: urosbajc/feedbacks:0.1
        name: feedbacks
        env:
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: bluemix
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_CONFIG_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_SERVER_BASEURL
            value: http://feedbacks:8090
        livenessProbe:
          httpGet:
            path: /health
            port: server
          initialDelaySeconds: 20
          periodSeconds: 3
        ports:
        - containerPort: 8090
          name: server
          protocol: TCP
        resources:
          requests:
            cpu: 150m
