apiVersion: v1
kind: Service
metadata:
  name: feedbacks
  labels:
    app: feedbacks
spec:
  type: NodePort
  ports:
  - name: server
    port: 8088
    protocol: TCP
    targetPort: 8088
  selector:
    app: feedbacks